services:
  - type: web
    name: ia-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: PORT
        fromService:
          type: web
          name: ia-backend
          property: port
    healthCheckPath: /
  - type: web
    name: ia-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: ia-backend
          property: host
  - type: managed
    name: ia-mongodb
    databaseName: ia-mongodb
    plan: free
